<?xml version="1.0"?>
<!--
 -
 - Transform the ISTLab data into HTML web pages
 -
 - (C) Copyright 2004 Diomidis Spinellis
 -
 - $Id$
 -
 -->

<!-- Global definitions {{{1 -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" />

	<!-- Member reference -->
	<xsl:template match="member">
		<a href="../members/{@id}.html">
		<xsl:if test="count(memb_title) != 0">
			<xsl:value-of select="memb_title"/>
			<xsl:text> </xsl:text>
		</xsl:if>
		<xsl:value-of select="givenname" />
		<xsl:text> </xsl:text>
		<xsl:value-of select="surname" />
		</a>
	</xsl:template>	

	<!-- main transformation {{{1 -->
	<xsl:template match="istlab">
		<html>
			<head>
				<title>ISTLab - phone catalog</title>
				<link href="../images/styles.css" type="text/css" rel="stylesheet" />
				<xsl:comment>Generated by $Id$</xsl:comment>
			</head>
			<body margin-left="0" margin-top="0">
			<div class="logo"><a href="http://istlab.dmst.aueb.gr/"><img src="../images/istlab-s.gif" alt="ISTLab" align="middle" border="0" /></a> The Research Center</div>
			<div class="projecttitle">
			PHONE Catalog
			</div>
			<table class="content">
				<tr>
					<td><b>Name</b></td>
					<td><b>Telephone</b></td>
					<td><b>e-mail</b></td>					
				</tr>
				<xsl:for-each select="current()/member_list/member">
				<xsl:if test="count(current()/alumnus) = 0">
				<tr>
					<td><xsl:apply-templates select="current()"/></td>
					<td><xsl:value-of select="current()/office_phone"/></td>
					<td><xsl:value-of select="substring-before(current()/email,'@')"/><b><xsl:text> at </xsl:text></b><xsl:value-of select="substring-after(current()/email,'@')"/></td>
				</tr>
				</xsl:if>				
				</xsl:for-each>
			</table>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
