name: Run Update Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # or any version you prefer

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown typogrify pybtex

    - name: Run Update Script
      run: |
        chmod +x bin/update # Make sure the script is executable
        bin/update
